name: BrowserStack Web Tests

on:
  workflow_call:
    inputs:
      SERVICE_LOCATION:
        required: true
        type: string
      BUILD_ARTIFACT:
        required: true
        type: string
    secrets:
      BROWSERSTACK_USERNAME:
        required: true
      BROWSERSTACK_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      S3_BUCKET:
        required: true    

jobs:
    web-test:
      runs-on: ubuntu-latest
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'   
    
      - name: Run tests
        run: |
           cd ${{ inputs.SERVICE_LOCATION }}
           mvn clean test -DtestngXmlFile="TestNg.xml"
        
      - name: Save test reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports
          path: ${{ inputs.SERVICE_LOCATION }}/${{ inputs.BUILD_ARTIFACT }}
        
      - name: Upload to S3
        if: success() || failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 
          S3_BUCKET: ${{ secrets.S3_BUCKET }}  
        run: |
          S3_OBJECT_KEY=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          aws s3 cp ${{ inputs.SERVICE_LOCATION }}/${{ inputs.BUILD_ARTIFACT }} s3://$S3_BUCKET/$S3_OBJECT_KEY/ --recursive 
